server:
  port: 8080
logging:
  level:
    cn.itsource: debug

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 212.64.50.83:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    max_idle_per_key: 5

# ===================================================================
# MYBATIS PLUS配置
# ===================================================================
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///fdfs2ibm?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: class*:cn/itsource/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

# ===================================================================
# IBM 对象存储配置
# ===================================================================
cos:
  api_key: LME14pL_DBa4VriQUA7X4mc7rj2hR-s9LY6G-uK7tISx
  service_instance_id: "crn:v1:bluemix:public:cloud-object-storage:global:a/3a0681143ecb45dc9bf321cfec0a5be6:25633186-9078-462e-92a6-f32050851a11::"
  endpoint_url: https://s3.jp-tok.cloud-object-storage.appdomain.cloud
  location: jp-tok
  bucket_name: solargen-test